# Generated by Django 5.0.6 on 2024-10-07 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('price_per_kg', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quality_acceptance', models.FloatField()),
                ('payment_terms', models.CharField(max_length=255)),
                ('pickup_schedule', models.CharField(max_length=255)),
            ],
        ),
    ]
