# Generated by Django 5.0.6 on 2024-10-10 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0002_weather_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='weather',
            name='description',
        ),
        migrations.AddField(
            model_name='weather',
            name='altitude',
            field=models.FloatField(default=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='weather',
            name='month',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='weather',
            name='rainfall',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='weather',
            name='soil_drainage',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='weather',
            name='soil_fertility',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='weather',
            name='soil_structure',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='weather',
            name='soil_type',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='weather',
            name='solar_radiation',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='weather',
            name='sunlight',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='weather',
            name='uv_radiation',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='weather',
            name='wind_speed',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='weather',
            name='year',
            field=models.PositiveIntegerField(default=2),
            preserve_default=False,
        ),
    ]
