# Generated by Django 5.0.6 on 2024-10-10 13:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0003_remove_weather_description_weather_altitude_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='weather',
            name='soil_type',
        ),
        migrations.RemoveField(
            model_name='weather',
            name='timestamp',
        ),
        migrations.AddField(
        model_name='weather',
        name='date',
        field=models.DateField(auto_now_add=True, default='2024-10-01'),  # Use a valid date
        ),

        migrations.AddField(
            model_name='weather',
            name='solar_type',
            field=models.CharField(default=2, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='weather',
            name='city',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='weather',
            name='humidity',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='weather',
            name='month',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='weather',
            name='soil_drainage',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='weather',
            name='soil_fertility',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='weather',
            name='soil_structure',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='weather',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='weather',
            name='year',
            field=models.IntegerField(),
        ),
    ]
