# Generated by Django 5.0.6 on 2024-10-10 13:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0004_remove_weather_soil_type_remove_weather_timestamp_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='weather',
            old_name='solar_type',
            new_name='soil_type',
        ),
    ]
